version: '3'
services:
  deploy:
    image: ${SERVICE:-automium/service-provisioner}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file:
      - ${CONFIG:-.env}
    network_mode: host
  upgrade:
    image: ${SERVICE:-automium/service-provisioner}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file: 
      - ${CONFIG:-.env}
    network_mode: host
    command: ./upgrade
  remove:
    image: ${SERVICE:-automium/service-provisioner}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file: 
      - ${CONFIG:-.env}
    network_mode: host
    command: ./remove
  apply:
    image: ${SERVICE:-automium/service-provisioner}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    env_file:
      - ${CONFIG:-.env}
    network_mode: host
    command: bash ./lib/apply.sh
