version: '3'
services:
  deploy:
    build:
      context: .
    volumes:
      - "/tmp/${CONFIG:-.env}_terraform:/usr/src/provisioner/.terraform"
  upgrade:
    build:
      context: .
    volumes:
      - "/tmp/${CONFIG:-.env}_terraform:/usr/src/provisioner/.terraform"
  apply:
    build:
      context: .
    volumes:
      - "/tmp/${CONFIG:-.env}_terraform:/usr/src/provisioner/.terraform"
